### PR TITLE
Init Project

### PR DESCRIPTION
**Pull request by quannb99**
## Related Tickets:
 * [#29290](https://edu-redmine.sun-asterisk.vn/issues/29290)
 
 ## WHAT this PR does?
 * Init project
 ## Notes Impacted Areas:
 * N/A.
 
 ## Attachments:
 * N/A

### CODE REVIEW

**Comment by moonelite99** [comment]
ready

**Comment by moonelite99** [comment]
ready

**Comment by quannb99** [comment]
ready

**Comment by quannb99** [comment]
ready

**Comment by quannb99** [comment]
ready

**Pull request merged**
